FROM ubuntu:20.04

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update -qq -y \
  && ACCEPT_EULA=Y apt-get upgrade -qq -y \
  && apt-get install --no-install-recommends -qq -y \
    curl python3 python3-dev python3-setuptools python3-pip libcurl4-openssl-dev libssl-dev \
  && apt-get clean -qq -y && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*